server:
  port: 23333
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:mysql://47.106.136.86:3306/SunoAi?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456@Panda
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    password: 123456@Panda
    host: 47.106.136.86
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#Redis


#JWT
signature: token!@#$%^7890
## MQTT##
mqtt:
  host: tcp://121.43.148.177:1883
  userName: yqhby2024
  passWord: yqhby2024&QSIOT
  qos: 1
  clientId: ClientId_local #ClientId_local必须唯一
  timeout: 10
  keepalive: 20
  topic1: lnsendout/yqhby2024/+/+/rtdata/#
  topic2: lnsendout/yqhby2024/+/+/alarm/#
#  topic3: ABCF
#  topic4: ABCH

pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true

